title: Connor Sullivan
logo: /assets/img/me.jpg
description: Ph.D. student interested in real-time systems and computer architecture.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
